import { poppins } from "./font";
import Navbar from "./Navbar"; // Import the client-side Navbar
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar /> {/* Use the client-side Navbar */}
        {children}
      </body>
    </html>
  );
}
